# Сборка приложения
ARG DOCKER_RUST_VERSION
FROM rust:$DOCKER_RUST_VERSION AS builder
ARG NGINX_ROOT_DIR
WORKDIR $NGINX_ROOT_DIR/app
#WORKDIR /usr/src/app
COPY app .
RUN cargo build --release

# Финальный образ
FROM debian:trixie
#RUN apt-get update && rm -rf /var/lib/apt/lists/*
WORKDIR $NGINX_ROOT_DIR/app/
ARG NGINX_ROOT_DIR
COPY --from=builder $NGINX_ROOT_DIR/app/target/release/server .
ARG RUST_PORT
EXPOSE $RUST_PORT
CMD $NGINX_ROOT_DIR/app/server
